server {
    listen       80;
    server_name  10.200.212.241;

    # 核心修复点：添加对 .mjs 的支持
    include       /etc/nginx/mime.types;
    types {
        application/javascript mjs;
        application/wasm       wasm;
        application/json       json;
        application/octet-stream bin;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # 允许跨域
        add_header 'Access-Control-Allow-Origin' '*';
    }

    # 开启 Gzip 提高 PlayCanvas 加载速度
    gzip on;
    gzip_types application/javascript application/json application/wasm text/css;
}